--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: sonbm
  name: minio
  labels:
    component: minio
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      component: minio
  template:
    metadata:
      labels:
        component: minio
    spec:
      volumes:
      - name: storage
        emptyDir: {}
      - name: config
        emptyDir: {}
      containers:
      - name: minio
        image: minio/minio:latest
        imagePullPolicy: IfNotPresent
        args:
        - server
        - --console-address
        - :9001
        - /storage
        - --config-dir=/config
        env:
        - name: MINIO_ROOT_USER
          value: "minio"
        - name: MINIO_ROOT_PASSWORD
          value: "minio123"
        ports:
        - name: data
          containerPort: 9000
        - name: web-ui
          containerPort: 9001
        volumeMounts:
        - name: storage
          mountPath: "/storage"
        - name: config
          mountPath: "/config"

---

apiVersion: v1
kind: Service
metadata:
  namespace: sonbm
  name: minio
  labels:
    component: minio
spec:
  type: ClusterIP
  ports:
    - name: data
      port: 9000
      targetPort: 9000
      protocol: TCP
    - name: web-ui
      port: 9001
      targetPort: 9001
      protocol: TCP

---
apiVersion: batch/v1
kind: Job
metadata:
  namespace: sonbm
  name: minio-setup
  labels:
    component: minio
spec:
  template:
    metadata:
      name: minio-setup
    spec:
      restartPolicy: OnFailure
      volumes:
      - name: config
        emptyDir: {}
      containers:
      - name: mc
        image: minio/mc:latest
        imagePullPolicy: IfNotPresent
        command:
        - /bin/sh
        - -c
        - "mc --config-dir=/config config host add velero http://minio:9000 minio minio123 && mc --config-dir=/config mb -p velero/velero"
        volumeMounts:
        - name: config
          mountPath: "/config"